name: CI

on:
  push:
    branches:
      - master

jobs:
  build: 

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v4.0.0
    
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Run Xunit tests
      continue-on-error: true
      run: dotnet test --no-restore --verbosity normal

  code-quality:

    runs-on: ubuntu-latest

    needs: build

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v4.0.0

    - name: Install SonarCloud
      run: dotnet tool install --global dotnet-sonarscanner

    - name: Analyze with SonarCloud
      run: dotnet sonarscanner begin /d:sonar.host.url="https://sonarcloud.io" /o:yashchavda-allata /key:YashChavda-Allata_ArcherDemoSeleniumProject /d:sonar.login=${{ secrets.SONAR_TOKEN }}
      
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Run Xunit tests
      continue-on-error: true
      run: dotnet test --no-restore --verbosity normal

    - name: Finalize SonarCloud analysis
      run: dotnet sonarscanner end /d:sonar.login=${{ secrets.SONAR_TOKEN }}

  stylecop:

    runs-on: ubuntu-latest

    needs: build

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v4.0.0

    - name: Install StyleCop
      run: dotnet tool install --global StyleCop.MSBuild

    - name: Run StyleCop
      run: dotnet build /p:StyleCopEnabled=true /p:StyleCopWriteResults=true
